"""MODULE_PROGRESS.md maintenance so an interrupted session can continue."""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from module_05_ppe.config_loader import MODULE_DIR, PROJECT_ROOT

STAGES = [
    "environment verified", "repository/project inspected", "dataset verified",
    "dataset prepared", "dataset split", "training started", "training epoch/checkpoint",
    "best model", "validation completed", "evaluation completed", "inference tested",
    "tests completed", "documentation completed",
]

DEFAULT_STATE: Dict[str, Any] = {
    "Current stage": "not started", "Completed stages": [], "Dataset": "Not available",
    "Model": "Not trained", "Latest checkpoint": "None", "Best checkpoint": "None",
    "Last successful epoch": "None", "Validation status": "Not measured",
    "Evaluation status": "Not measured", "Tests status": "Not run",
    "Inference status": "Not tested", "Documentation status": "Not started",
    "Remaining tasks": [], "Next action": "", "Known issues": [],
}


class ProgressTracker:
    """Keeps a JSON state file and renders it to MODULE_PROGRESS.md."""

    def __init__(self, json_path: Optional[Path] = None, md_path: Optional[Path] = None):
        self.json_path = Path(json_path or MODULE_DIR / "logs" / "progress.json")
        self.md_path = Path(md_path or PROJECT_ROOT / "MODULE_PROGRESS.md")
        self.state = self._load()

    def _load(self) -> Dict[str, Any]:
        state = json.loads(json.dumps(DEFAULT_STATE))
        if self.json_path.is_file():
            try:
                state.update(json.loads(self.json_path.read_text(encoding="utf-8")))
            except (json.JSONDecodeError, OSError):
                pass
        return state

    def update(self, **fields: Any) -> None:
        """Set fields using python-friendly names, e.g. update(best_checkpoint='...')."""
        for key, value in fields.items():
            self.state[key.replace("_", " ").capitalize()] = value
        self._save()

    def complete(self, stage: str, next_action: Optional[str] = None) -> None:
        if stage not in self.state["Completed stages"]:
            self.state["Completed stages"].append(stage)
        self.state["Current stage"] = stage
        if next_action is not None:
            self.state["Next action"] = next_action
        self._save()

    def add_issue(self, text: str) -> None:
        if text not in self.state["Known issues"]:
            self.state["Known issues"].append(text)
        self._save()

    def _save(self) -> None:
        self.state["Last updated (UTC)"] = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
        self.json_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.json_path.with_suffix(".tmp")
        tmp.write_text(json.dumps(self.state, indent=2), encoding="utf-8")
        os.replace(tmp, self.json_path)
        self.md_path.write_text(self.render(), encoding="utf-8")

    def render(self) -> str:
        s = self.state
        lines = ["# MODULE_PROGRESS - NEXORA Module 05 (module_05_ppe)", "",
                 "_Generated by module_05_ppe/progress.py - read this first when resuming._", ""]
        for key in DEFAULT_STATE:
            value = s.get(key)
            if isinstance(value, list):
                lines.append(f"**{key}:**" + ("" if value else " none"))
                lines += [f"- {item}" for item in value]
            else:
                lines.append(f"**{key}:** {value}")
            lines.append("")
        lines.append(f"_Last updated (UTC): {s.get('Last updated (UTC)', 'n/a')}_")
        return "\n".join(lines) + "\n"
